### ISSUE TITLE
MVC bitrate scanning on 3D blu-ray doesn't work

### ISSUE THREAD

**Issue by nautilus7** [UniqProject/BDInfo#12]
As the title says, the bitrate scanning of MVC video streams (those found on 3D blu-ray's) doesn't seem to work. It always displays 0 kbps.

I tested on more than one discs, so I guess it's a general problem and I won't have to provide a sample. If a sample is needed though, please let me know.

I remind you that the bitrate was showing correctly on the original 0.5.8 version of bdinfo.

**Comment by vandenk** [comment]
Same problem with the latest version (BDInfo 0.7.5.3) ...
Yet with BDInfo 0.5.8 it works !
![bdinfo](https://user-images.githubusercontent.com/11425010/50313035-6eb7c700-04aa-11e9-947a-d9eff98d1d5c.jpg)

**Comment by UniqProject** [comment]
Fixed in 0.7.5.4. Somehow WIP code has slipped through...

**Comment by vandenk** [comment]
Ok Thanks !
