### ISSUE TITLE
7.1 chan DTS-HDMA not detected

### ISSUE THREAD

**Issue by markfilipak-windows** [UniqProject/BDInfo#17]
Re, "Star Trek, The Next Generation" 41 BD collection marked "THE FULL JOURNEY" EAN 5051368261935, Disks Season 7, Disc 1, 2, 3, 4, 5, 6 (i.e., all 6 discs).

As with the other 35 discs in this collection, the 6 discs for Season 7 primary audio (English) is 7.1 chan DTS-HDMA -- confirmed in VLC & PDVD. BDInfo 0.7.5.5 thinks it is 2 chan DD @ 192 K-bit/sec. BDInfo 0.5.8 also gets it wrong.

**Comment by markfilipak-windows** [comment]
I took a screen shot showing BDInfo & VLC's codec tool side-by-side.
![STAR TREK TNG  1987-1994  S7 D1 'THE FULL JOURNEY' 5051368261935  2016  ABC BD-50 ](https://user-images.githubusercontent.com/45295408/58658831-71d3a080-82ef-11e9-80ea-229401169596.png)

**Comment by markfilipak-windows** [comment]
And here is the same disc viewed via BDedit.
![STAR TREK TNG  1987-1994  S7 D1 'THE FULL JOURNEY' 5051368261935  2016  ABC BD-50 BDedit](https://user-images.githubusercontent.com/45295408/58661472-04773e00-82f6-11e9-9b6d-b8843d26456f.png)
Kindly let me know if I can help further.

**Comment by markfilipak-windows** [comment]
I don't know how this got closed, and I don't know how to open it again.

**Comment by markfilipak-windows** [comment]
I must have accidentally closed this issue. Well, I discovered how to open it again.

**Comment by markfilipak-windows** [comment]
Ah! I see. the [Close and comment] button closes the issue. That's surprising.

**Comment by markfilipak-windows** [comment]
Is there anything further that you folks would like me to do? I have some tools that might reveal why the 7.1 DTS-HD MA is being detected as 2.0 DD but I may need some guidance for troubleshooting as I'm not 100% conversant with the MPLS & M2TS data structures.

To clarify: This is a 41 disc box set. The problem occurs only for the 6 discs of "Star Trek, TNG" season 7. For the other 34 discs, DBInfo correctly identifies 7.1 DTS-HD MA. The box set is "Star Trek, TNG, THE FULL JOURNEY" EAN 5051368261935. I assume that the discs in this set are identical to the discs in the individual season box sets from England, so the isolated season 7 box set probably also exhibits this fault.

**Comment by UniqProject** [comment]
Are you able to provide a sample of those discs that are being reported wrong? 
The BD structure with the first 100MB of the episode .m2ts should be sufficient

**Comment by markfilipak-windows** [comment]
Yes, I can/will provide whatever you want. Can you clarify your request? What does "BD structure" mean, specifically?

Regarding "the first 100MB of the episode .m2ts", the problem is all episodes of all 6 discs that comprise Season 7 of StarTrek TNG. I will arbitrarily select one. Where should I deposit the 100MB?

**Comment by UniqProject** [comment]
Basically a zip/rar/7z archive of the BDMV folder, containing all files inside the subfolders marked with green, 
and the first 100-200MB of the problematic .m2ts inside the "STREAM" folder
![image](https://user-images.githubusercontent.com/3046095/101242872-9c7c9180-36fc-11eb-8810-649b0c2ff29c.png)

I do not have any specific place for samples, you can use either mediafire or one of the cloud services (like GDrive/OneDrive/DropBox etc.) that allows sharing files.

Thanks

**Comment by markfilipak-windows** [comment]
Well, I created a 14.7 GiB ISO with one episode that actually plays the episode, but I don't have any way to get it to you. I tried going to the sites you suggested but I'm not going to pay. Sorry.

With the hope that it will help, I'm attaching 00000.mpls.

...Ah... It looks like I can't even do that. I tried, but the mpls is not showing up here. I don't know why. Sorry.

**Comment by markfilipak-windows** [comment]
I added '.zip' to '00000.mpls'. Let's see if that works.

**Comment by markfilipak-windows** [comment]
Nope. Didn't work.

Gawd, github is awful.

**Comment by UniqProject** [comment]
If you still want to give it a shot, I have created a small tool to create samples.
[BDInfoSampleCopy.zip](https://github.com/UniqProject/BDInfo/files/5660545/BDInfoSampleCopy.zip)
It will be available in the next release. (Don't extract it in the same folder as BDInfo for now, or it may break BDInfo functionality)


The tool will generate a folder with working BD structure and a 100-300 MB stream file, which you then can zip and upload (MediaFire uploads are free up to 1GB)

**Comment by markfilipak-windows** [comment]
Thanks, I'll give it a go. It doesn't explain why I couldn't upload the MPLS to here, though. The MPLS is only 1358 bytes. Why do developers use github? It's just dreadful. The so-called rich text is a pain and the 3-dot menu doesn't work.

**Comment by markfilipak-windows** [comment]
Is BDInfoSampleCopy done?

105,209,965 bytes in 114 files

STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00000.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00001.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00002.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00003.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00004.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00005.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00006.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00007.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00008.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00009.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00010.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00011.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00012.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00013.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00014.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00015.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00016.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00017.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00018.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00019.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00020.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00021.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00022.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00023.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00024.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00025.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00026.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00027.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00028.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00029.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00030.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00031.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00032.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00033.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00034.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00035.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00036.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00037.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00038.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00039.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00040.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00041.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00042.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00043.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00044.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00045.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00046.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00047.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00048.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00049.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00050.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00051.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00052.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00053.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00054.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00055.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00056.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00057.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00058.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00059.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00060.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00061.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00062.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00063.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00064.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00065.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00066.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00067.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00068.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00069.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00070.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\CLIPINF\00071.clpi
STAR TREK TNG SEASON 7 DISC 1BDMV\index.bdmv
STAR TREK TNG SEASON 7 DISC 1BDMV\META\DL\bdmt_eng.xml
STAR TREK TNG SEASON 7 DISC 1BDMV\META\DL\TNGs2PS3_Thumbnail416_result.jpg
STAR TREK TNG SEASON 7 DISC 1BDMV\META\DL\TNGs2PS3_Thumbnail640_result.jpg
STAR TREK TNG SEASON 7 DISC 1BDMV\MovieObject.bdmv
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00000.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00001.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00002.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00003.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00004.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00005.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00006.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00007.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00008.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00009.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00011.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00016.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00017.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00018.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00019.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00020.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00021.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00022.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00023.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00024.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00025.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00026.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00027.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00028.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00029.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00030.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00031.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00032.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00033.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00034.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00035.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00036.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00037.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00038.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00040.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\PLAYLIST\00041.mpls
STAR TREK TNG SEASON 7 DISC 1BDMV\STREAM\00004.m2ts

**Comment by markfilipak-windows** [comment]
It's uploaded to MediaFire. Name: "7.1 chan DTS-HDMA not detected #17.ZIP". Now what do I do?

**Comment by UniqProject** [comment]
Thanks,
please copy the share link using this icon next to the uploaded filename
![image](https://user-images.githubusercontent.com/3046095/101527455-52124380-398e-11eb-8d3f-406369d3d3f3.png)

and paste it here using this icon
![image](https://user-images.githubusercontent.com/3046095/101527638-8d147700-398e-11eb-9c9e-6cb51f136372.png)

like this (just paste it twice between the round and square brackets):
![image](https://user-images.githubusercontent.com/3046095/101528095-20e64300-398f-11eb-9814-a89213cd4c60.png)

[http://www.mediafire.com/file/luv036al91zrsr4/BDInfoSampleCopy.zip/file](http://www.mediafire.com/file/luv036al91zrsr4/BDInfoSampleCopy.zip/file)

**Comment by markfilipak-windows** [comment]
The link icon here in the ribbon bar above does nothing (github sucks).

http://www.mediafire.com/file/y1nr7q5r4zz2mpo/7.1_chan_DTS-HDMA_not_detected_%252317.ZIP/file
http://www.mediafire.com/file/y1nr7q5r4zz2mpo/7.1_chan_DTS-HDMA_not_detected_%252317.ZIP/file

**Comment by UniqProject** [comment]
Thanks, got the file.
Will check it out.

**Comment by markfilipak-windows** [comment]
Good hunting!

**Comment by UniqProject** [comment]
Interesting...
In the playlist:
1st referenced stream file (0004.m2ts - episode) has 7.1 DTS-HD MA as first audio stream (ID 0x1100/4352),
2nd referenced stream file (00005.m2ts - (post) credits I guess) has 2.0 AC3 as first audio stream (ID 0x1100/4352).

Seamless branching at its best...

Will have to work around small intro/outro clips...

**Comment by markfilipak-windows** [comment]
Seamless branching: Ginger Rogers made all the steps that Fred Astaire made while walking backwards!

**Comment by UniqProject** [comment]
Please try latest beta release [v0.7.5.8b](https://github.com/UniqProject/BDInfo/releases/tag/v0.7.5.8b)

**Comment by markfilipak-windows** [comment]
Except for one thing, you've fixed the problem.

The one thing is this:
Audio: English / DTS-HD Master Audio / 7.1 / 48 kHz /  5094 kbps / 24-bit (DTS Core: 5.1 / 48 kHz /  1509 kbps / 24-bit)
"5094 kbps" seems awfully high. Are you sure?

Somewhat related: May I send you a private message?

**Comment by markfilipak-windows** [comment]
About the "5094 kbps", never mind. I just checked and that is in line with the episodes in the previous seasons.

I would still like to send you a PM.

**Comment by markfilipak-windows** [comment]
Thanks for the beta and the improvements for UHD displays. Good work! I think I can now retire version 0.5.8.
