### ISSUE TITLE
Need bytes, not MB or GB

### ISSUE THREAD

**Issue by markfilipak-windows** [UniqProject/BDInfo#18]
In the main (MPLS) window, BDInfo 0.5.8 shows 'Estimated Bytes' & 'Measured Bytes' as bytes, whereas BDInfo 0.7.5.5 shows them as MB & GB. I need bytes in order to suss out small differences between videos, and also because of the confusion between MB, GB, MiB, and GiB. The report is in bytes and I need the window display to also be in bytes.

**Comment by d4rkne55** [comment]
I think showing it humanly formatted in the main window makes sense, it's the first overview of the streams and it's easier to get an idea how big a stream is. The columns should be renamed though, as it doesn't show "Bytes" anymore, should rather be "Estimated Size".
Now, as you said yourself, you see the precise amount of bytes in the report; why is that not enough? I mean, the report is generated almost immediately, it's not like you need to wait for it.

**Comment by markfilipak-windows** [comment]
I don't want an estimate. I need the actual bytes. A report is not needed for that: For DVD 'VOB' files having several videos, i.e. several PGCs (program chains), the number of bytes of each video is available in the associated 'IFO' files; For BD videos with branching, the number of bytes in each branch is available (I think) in 'mpls' files. Getting those byte sizes doesn't require that a full scan & report be done. In addition to avoiding doing a scan & report, those numbers would also be useful for initial selection in those cases where a selective scan and report is wanted. A scan & report should not be needed to produce those byte sizes and not showing byte sizes in the main window just creates a stumbling block. What's the point of making an application less capable, eh?

**Comment by d4rkne55** [comment]
Ah, I haven't thought about needing to do a scan first before getting the report.^^ Makes sense then, if the info is readily available, showing it before the scan is helpful.

**Comment by UniqProject** [comment]
Hi, 
afaik, the BluRay playlists do not contain any filesize information, only runtime of each playlist entry, so until you do a full scan, every reported file/title size is just a wild guess/estimation.
[https://github.com/lw/BluRay/wiki/MPLS](https://github.com/lw/BluRay/wiki/MPLS)

The estimated size and measured size will only match if the total runtime of the playlist matches the total runtime of the clips that are used in this playlist. Otherwise it will be calculated based on the runtime and average bitrate of the included clips.

**Comment by markfilipak-windows** [comment]
@UniqProject

Thanks for the link.

As far as I know, the file sizes can simply be read from the media and the 'mpls' contains a link list of branches in those rare cases where branching is employed. So, it should be possible to precisesly know a BD video's byte size prior to scanning. I will peruse the link you gave me. Perhaps I'm wrong, but the 'mpls' file is the key. It's what a player uses to assemble a BD MPEG stream.

**Comment by markfilipak-windows** [comment]
Sorry. I just realized that this is your site, that you are DA MAN. I didn't mean to talk down to you. I'm sure you know all there is to know and I'll stop being stupid. Best Regards to You. Be Happy. Be Healthy.

Mark.

**Comment by UniqProject** [comment]
All good, I am not offended in any way.

> As far as I know, the file sizes can simply be read from the media and the 'mpls' contains a link list of branches in those rare cases where branching is employed. So, it should be possible to precisesly know a BD video's byte size prior to scanning. I will peruse the link you gave me. Perhaps I'm wrong, but the 'mpls' file is the key. It's what a player uses to assemble a BD MPEG stream.

This is exactly what "Estimated Size" column is reporting. A total filesize of all M2TS files included in the playlist.
And as I already mentioned before, the "Estimated Size" and "Measured Size" might be different, if the playlist references only a part of the stream (even if it is only 1 M2TS, there is no guarantee that the playlist is referencing the complete stream file). I have seen BDs with multiple playlists referencing different (small) parts of the same m2ts, where estimated size ended being 4-5x times bigger than measured size.
Seamless branching takes the whole story to another level. 

This is why I said, any reported filesizes without a full scan are just a wild guess

**Comment by markfilipak-windows** [comment]
Ah! Now I see what the problem is, and it's my fault.

I look at the 'Measured Size' column, not the 'Estimated Size' column. I really only care about 'Measured Size'. Could that be in bytes, please?

**Comment by UniqProject** [comment]
Untick this setting and it will display it as bytes
![image](https://user-images.githubusercontent.com/3046095/101616097-38651080-3a0f-11eb-84c1-968fe83d381e.png)

![image](https://user-images.githubusercontent.com/3046095/101616127-44e96900-3a0f-11eb-8a8a-0f202badf240.png)

**Comment by markfilipak-windows** [comment]
Ah! Thanks, There's so much to admire here. The way you size columns and panels is brilliant. I've never seen such an intelligent approach. You should patent it.
