### ISSUE TITLE
Window text size problem

### ISSUE THREAD

**Issue by markfilipak-windows** [UniqProject/BDInfo#19]
I have a UHD display. When I first open BDInfo 0.7.5.5, the window text is good. And if I click [Rescan] button, the window text is good. But if click either [Browse...] or [ISO] button, the window text becomes too small to read.

**Comment by UniqProject** [comment]
Thanks for the report.
I don't have a UHD display, but it seems to be a general problem with HighDPI Settings.
Solution will be available in the next release

**Comment by UniqProject** [comment]
Please try v0.7.5.6

**Comment by markfilipak-windows** [comment]
Congratulations on the new version. And congratulations and thanks for fixing the UHD font-size problem. Now, there's a new problem: https://github.com/UniqProject/BDInfo/issues/27

...I would have put the URL above in a link, but the format controls and the menu (...) don't work. Sigh! I wish github would default to plain text. Oh, well.
