### ISSUE TITLE
Disc size of 3D-Bluray is doubled when loaded as ISO

### ISSUE THREAD

**Issue by hurda** [UniqProject/BDInfo#2]
BD-Info 0.72 and 0.73

The "Disk Size" is twice the size of the streams when loading a 3D-BD in ISO-mode.
Mounting the ISO and scanning the virtual drive does not show this error.

Tested with the ISO-samples from https://kodi.wiki/view/Samples#3D_Test_Clips

**Comment by UniqProject** [comment]
Thanks for the samples. Should be fixed now.

**Comment by hurda** [comment]
It is, thanks!
