### ISSUE TITLE
HDR10+ support

### ISSUE THREAD

**Issue by psychoboust** [UniqProject/BDInfo#20]
Hello, HDR10+ support is missing.
Is it possible to add it ?
Thks a lot

**Comment by UniqProject** [comment]
First of all, sorry for a late response.

Can you provide any samples?
I do not have a single HDR10+ disc on my side, so I can't test any change on this topic.

Edit: I just have seen there is a pull request. Will check it out

**Comment by UniqProject** [comment]
Added in 0dac221cedfdff96805ca3f400b636ad98b1e61a

 Thanks @stanionascu for the code.

Please test v.0.7.5.6 and feedback.

**Comment by psychoboust** [comment]
@UniqProject thanks it does work.
Now HDR10+ is displayed.
Just one thing, there is a regression in this release, when I click on the ISO button it look for *..ISO (there is 2 dots) so it finds no file.

**Comment by UniqProject** [comment]
Cool, thanks for feedback.
The regression was already reported in #27 and fixed.
Expect next release soon.
