### ISSUE TITLE
Incorrect "Left Eye" reporting on non-3D BDs with multiple video streams

### ISSUE THREAD

**Issue by d4rkne55** [UniqProject/BDInfo#26]
I came across the issue now, that BDInfo outputs "Left Eye" on the video streams of my Transformers BD.
I was first thinking that the video stream is just one side of a 3D source, still with some flag that BDInfo reads out, but I couldn't find anything 3D for the first Transformers movie from 2007.

Checking the following commit explains why: 5263eb6ff871c876ab3f0a00b645cec800756a60

The video stream is a regular AVC encode, not 3D, and the playlist doesn't have this BaseView flag, _but_ the playlist contains two video streams (the second one hidden, but doesn't matter for this). Probably this is just a stream for PiP?
```
VIDEO:

Codec                   Bitrate             Description     
-----                   -------             -----------     
MPEG-4 AVC Video        31414 kbps          Left Eye / 1080p / 23.976 fps / 16:9 / High Profile 4.1
* MPEG-4 AVC Video      690 kbps            Left Eye / 480p / 23.976 fps / 16:9 / High Profile 3.2
```
It sets the BaseView info to `false` then. And that BaseView property decides then whether it's the left or right eye stream in the output, if it's set.

**Comment by UniqProject** [comment]
Thanks, will have a look

**Comment by d4rkne55** [comment]
Ah, didn't catch the `is3D` property. And that was quick.^^
