### ISSUE TITLE
Secondary AC3 audio stream is not detected when primary stream is Dolby TrueHD or Atmos

### ISSUE THREAD

**Issue by nautilus7** [UniqProject/BDInfo#3]
As the title says, the ac3 stream is not always detected when the primary stream is a truehd or an atmos one.

Example 1: Blade Runner 2049 BD

With BDInfo:

> Disc Size: 49.211.251.020 bytes
> Protection: AACS
> BD-Java: Yes
> Playlist: 00002.MPLS
> Size: 0 bytes
> Length: 2:43:47.818
> Total Bitrate: 0,00 Mbps
> Video: MPEG-4 AVC Video / 0 kbps / 1080p / 23,976 fps / 16:9 / High Profile 4.1
> Audio: English / DTS-HD Master Audio / 5.1 / 48 kHz / 24-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 24-bit)
> Audio: English / Dolby Digital Audio / 5.1 / 48 kHz / 640 kbps / DN -4dB
> Audio: French / Dolby Digital Audio / 5.1 / 48 kHz / 640 kbps / DN -4dB
> Audio: Spanish / Dolby Digital Audio / 5.1 / 48 kHz / 640 kbps / DN -4dB
> Audio: English / Dolby TrueHD + Atmos / 7.1 / 48 kHz / 24-bit (AC3 Embedded: )

With eac3to:

> Z:\Blade Runner 2049 2017>eac3to 1)
> M2TS, 1 video track, 5 audio tracks, 5 subtitle tracks, 2:43:48, 24p /1.001
> 1: Chapters, 16 chapters
> 2: h264/AVC, 1080p24 /1.001 (16:9)
> 3: DTS Master Audio, English, 5.1 channels, 24 bits, 48kHz
>    (core: DTS, 5.1 channels, 1509kbps, 48kHz)
> 4: AC3, English, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB
> 5: AC3, French, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB
> 6: AC3, Spanish, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB
> 7: TrueHD/AC3 (Atmos), English, 7.1 channels, 48kHz
>    (embedded: AC3 EX, 5.1 channels, 448kbps, 48kHz, dialnorm: -27dB)

Example 2: Crouching Tiger Hidden Dragon UHD:

With BDInfo:

> Disc Size: 91.794.732.842 bytes
> Protection: AACS
> BD-Java: Yes
> Playlist: 00001.MPLS
> Size: 0 bytes
> Length: 2:00:12.204
> Total Bitrate: 0,00 Mbps
> Video: HEVC Video / 0 kbps / 2160p / 23,976 fps / 16:9
> Audio: Chinese / Dolby TrueHD + Atmos / 7.1 / 48 kHz / 24-bit
> Audio: Chinese / Dolby TrueHD + Atmos / 7.1 / 48 kHz / 24-bit
> Audio: English / DTS-HD Master Audio / 5.1 / 48 kHz / 16-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 16-bit)
> Audio: Czech / Dolby Digital Audio / 5.1 / 48 kHz / 448 kbps
> Audio: French / Dolby Digital Audio / 5.1 / 48 kHz / 448 kbps
> Audio: Hungarian / Dolby Digital Audio / 5.1 / 48 kHz / 448 kbps
> Audio: Japanese / Dolby Digital Audio / 5.1 / 48 kHz / 448 kbps
> Audio: Polish / Dolby Digital Audio / 5.1 / 48 kHz / 448 kbps
> Audio: Portuguese / Dolby Digital Audio / 5.1 / 48 kHz / 448 kbps
> Audio: Russian / Dolby Digital Audio / 5.1 / 48 kHz / 448 kbps
> Audio: Spanish / Dolby Digital Audio / 5.1 / 48 kHz / 448 kbps
> Audio: Thai / Dolby Digital Audio / 5.1 / 48 kHz / 448 kbps
> Audio: English / Dolby Digital Audio / 2.0 / 48 kHz / 192 kbps / Dolby Surround
> Audio: English / Dolby Digital Audio / 2.0 / 48 kHz / 192 kbps
> Audio: English / Dolby Digital Audio / 2.0 / 48 kHz / 192 kbps / Dolby Surround
> Audio: English / Dolby Digital Audio / 2.0 / 48 kHz / 192 kbps / Dolby Surround

With eac3to:

> Z:\Crouching Tiger Hidden Dragon 2000>eac3to 1)
> The program type (4781) changes from subtitle to audio.
> M2TS, 1 video track, 16 audio tracks, 29 subtitle tracks, 77.181p
> 1: Chapters, 16 chapters
> 2: h265/HEVC, 2160p24 /1.001 (16:9), 10 bits
> 3: TrueHD/AC3 (Atmos), Chinese, 7.1 channels, 48kHz
>    (embedded: AC3, 5.1 channels, 640kbps, 48kHz)
> 4: TrueHD/AC3 (Atmos), Chinese, 7.1 channels, 48kHz
>    (embedded: AC3, 5.1 channels, 640kbps, 48kHz)
> 5: DTS Master Audio, English, 5.1 channels, 16 bits, 48kHz
>    (core: DTS, 5.1 channels, 1509kbps, 48kHz)
> 6: AC3, Czech, 5.1 channels, 448kbps, 48kHz, -13ms
> 7: AC3, French, 5.1 channels, 448kbps, 48kHz, -13ms
> 8: AC3, Hungarian, 5.1 channels, 448kbps, 48kHz, -13ms
> 9: AC3, Japanese, 5.1 channels, 448kbps, 48kHz, -13ms
> 10: AC3, Polish, 5.1 channels, 448kbps, 48kHz, -13ms
> 11: AC3, Portuguese, 5.1 channels, 448kbps, 48kHz, -13ms
> 12: AC3, Russian, 5.1 channels, 448kbps, 48kHz, -13ms
> 13: AC3, Spanish, 5.1 channels, 448kbps, 48kHz, -13ms
> 14: AC3, Thai, 5.1 channels, 448kbps, 48kHz, -13ms
> 15: AC3 Surround, English, 2.0 channels, 192kbps, 48kHz, -13ms
> 16: AC3, English, 2.0 channels, 192kbps, 48kHz, -13ms
> 17: AC3 Surround, English, 2.0 channels, 192kbps, 48kHz, -11ms
> 18: AC3, English, 2.0 channels, 192kbps, 48kHz, -11ms

**Comment by UniqProject** [comment]
How many discs are affected by this?
I am running tests on my library, but can't reproduce this behaviour so far.

**Comment by nautilus7** [comment]
Hi, thanks for the reply.

Well, I tested 3 discs that I had in my hard disc and 2 of them had the issue. I will test more and try to find some pattern, so you can reproduce it.

**Comment by nautilus7** [comment]
I tried another ~10 discs and none of them has this issue. So I uploaded a [sample](https://www72.zippyshare.com/v/6nuJZ4Xa/file.html) of the Blade Runner disc that has it, in case that helps. It's the complete bd structure with only a small piece of the main movie m2ts file.

**Comment by UniqProject** [comment]
Thanks, I could not reproduce it on my discs either.
However, with your sample I think I may have fixed this, please try this one:
[BDInfo_v0.7.3.3b.zip](https://github.com/UniqProject/BDInfo/files/1976729/BDInfo_v0.7.3.3b.zip)

**Comment by nautilus7** [comment]
Yes, actually both of my discs that didn't display the embedded ac3 track work ok now. Thanks for the quick fix!

**Comment by UniqProject** [comment]
Awesome!
