### ISSUE TITLE
Bitrate TrueHD

### ISSUE THREAD

**Issue by XinfitX** [UniqProject/BDInfo#6]
hello, I'm just comparing the bdinfo of my bluray, for which reason we have two different values

> DISC INFO:
> 
> Disc Title:     Darkest.Hour.2017.1080p.Blu-ray.AVC.TrueHD.7.1
> Disc Size:      42.131.392.003 bytes
> Protection:     AACS
> BD-Java:        Yes
> BDInfo:         0.7.3.3
> 
> PLAYLIST REPORT:
> 
> Name:                   00800.MPLS
> Length:                 2:04:54.487 (h:m:s.ms)
> Size:                   38.837.200.896 bytes
> Total Bitrate:          41,46 Mbps
> 
> VIDEO:
> 
> Codec                   Bitrate             Description     
> -----                   -------             -----------     
> MPEG-4 AVC Video        31590 kbps          1080p / 23,976 fps / 16:9 / High Profile 4.1
> 
> AUDIO:
> 
> Codec                           Language        Bitrate         Description     
> -----                           --------        -------         -----------     
> Dolby TrueHD + Atmos            English         **4218 kbps**       7.1 / 48 kHz / 4218 kbps / 24-bit (AC3 Embedded: 5.1 / 48 kHz / 640 kbps / DN -4dB)
> Dolby Digital Plus Audio        Spanish         768 kbps        7.1 / 48 kHz / 768 kbps (DD+ Embedded: 5.1 / 48 kHz / 448 kbps)
> Dolby Digital Audio             French          640 kbps        5.1 / 48 kHz / 640 kbps / DN -4dB
> Dolby Digital Audio             English         192 kbps        2.0 / 48 kHz / 192 kbps / DN -4dB / Dolby Surround
> Dolby Digital Audio             English         192 kbps        2.0 / 48 kHz / 192 kbps / DN -4dB / Dolby Surround
> 
> SUBTITLES:
> 
> Codec                           Language        Bitrate         Description     
> -----                           --------        -------         -----------     
> Presentation Graphics           English         37,182 kbps                     
> Presentation Graphics           Spanish         40,006 kbps                     
> Presentation Graphics           French          35,765 kbps                     
> Presentation Graphics           Spanish         1,115 kbps                      
> Presentation Graphics           French          0,871 kbps                      
> 
> FILES:
> 
> Name            Time In         Length          Size            Total Bitrate   
> ----            -------         ------          ----            -------------   
> 00800.M2TS      0:00:00.000     2:04:54.487     38.837.200.896  41.457      

> DISC INFO:
> 
> Disc Title:     Darkest.Hour.2017.1080p.Blu-ray.AVC.TrueHD.7.1
> Disc Size:      42,131,391,847 bytes
> Protection:     AACS
> BD-Java:        Yes
> BDInfo:         0.5.8.7 (compatible layout created by DVDFab 10.0.8.1)
> 
> PLAYLIST REPORT:
> 
> Name:                   00800.MPLS  
> Length:                 2:04:54.487 (h:m:s.ms)
> Size:                   38,837,200,896 bytes
> Total Bitrate:          41.46 Mbps
> 
> VIDEO:
> 
> Codec                   Bitrate             Description     
> -----                   -------             -----------     
> MPEG-4 AVC Video        31590 kbps          1080p / 23.976 fps / 16:9 / High Profile 4.1 / 
> 
> AUDIO:
> 
> Codec                           Language        Bitrate         Description     
> -----                           --------        -------         -----------     
> Dolby Atmos/TrueHD Audio        English         **4858 kbps**       7.1-Atmos / 48 kHz / 4858 kbps / 24-bit (AC3 Core: 5.1 / 48 kHz / 640 kbps)
> Dolby Digital Plus Audio        Spanish         768 kbps        7.1 / 48 kHz / 768 kbps
> Dolby Digital Audio             French          640 kbps        5.1 / 48 kHz / 640 kbps
> Dolby Digital Audio             English         192 kbps        2.0 / 48 kHz / 192 kbps / Dolby Surround
> Dolby Digital Audio             English         192 kbps        2.0 / 48 kHz / 192 kbps / Dolby Surround
> 
> SUBTITLES:
> 
> Codec                           Language        Bitrate         Description     
> -----                           --------        -------         -----------     
> Presentation Graphics           English         37.183 kbps                     
> Presentation Graphics           Spanish         40.006 kbps                     
> Presentation Graphics           French          35.765 kbps                     
> Presentation Graphics           Spanish         1.115 kbps                      
> Presentation Graphics           French          0.871 kbps                      
> 
> FILES:
> 
> Name            Time In         Length          Size            Total Bitrate   
> ----            -------         ------          ----            -------------   
> 00800.M2TS      0:00:00.000     2:04:54.487     38,837,200,896  41,456 kbps

eac3to v3.34
command line: eac3to.exe  -check 
------------------------------------------------------------------------------
M2TS, 1 video track, 5 audio tracks, 5 subtitle tracks, 2:04:54, 24p /1.001
1: Chapters, 20 chapters
2: h264/AVC, 1080p24 /1.001 (16:9)
3: TrueHD/AC3 (Atmos), English, 7.1 channels, 48kHz
  (embedded: AC3, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB)
4: E-AC3, Spanish, 7.1 channels, 768kbps, 48kHz, dialnorm: -27dB
  (core: AC3, 5.1 channels, 448kbps, 48kHz, dialnorm: -27dB)
5: AC3, French, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB
6: AC3 Surround, English, 2.0 channels, 192kbps, 48kHz, dialnorm: -27dB
7: AC3 Surround, English, 2.0 channels, 192kbps, 48kHz, dialnorm: -27dB
8: Subtitle (PGS), English
9: Subtitle (PGS), Spanish
10: Subtitle (PGS), French
11: Subtitle (PGS), Spanish
12: Subtitle (PGS), French
[s10] Extracting subtitle track number 10...
[s09] Extracting subtitle track number 9...
[a05] Extracting audio track number 5...
[a06] Extracting audio track number 6...
[s11] Extracting subtitle track number 11...
[s08] Extracting subtitle track number 8...
[v02] Extracting video track number 2...
[s12] Extracting subtitle track number 12...
[a04] Extracting audio track number 4...
[a07] Extracting audio track number 7...
[a03] Extracting audio track number 3...
Video track 2 contains 179688 frames.
Subtitle track 8 contains 1814 captions.
Subtitle track 9 contains 1821 captions.
Subtitle track 10 contains 1804 captions.
Subtitle track 11 contains 45 captions.
Subtitle track 12 contains 42 captions.
eac3to processing took 9 minutes, 43 seconds.
Done.

**Comment by UniqProject** [comment]
It was reported in #4 already.
DVDFab is reporting the overall bitrate of TrueHD **and** the Core Stream as Bitrate. 
BDInfo up to version 0.7.3.3 reported only the Bitrate of HD stream, which is more accurate, but affects the overall bitrate.

I've changed the behaviour in ea35723 and 72604c3 

The next update will report TrueHD audio streams like this:
Dolby TrueHD/Atmos Audio English **4858** kbps 7.1-Atmos / 48 kHz / **4218** kbps / 24-bit (AC3 Core: 5.1 / 48 kHz / 640 kbps)

The first reported bitrate will be the overall bitrate (HD+Core streams), and the second bitrate in the description will only report bitrate of HD stream

**Comment by XinfitX** [comment]
thanks very much, looking for future updates, great work !!
