### ISSUE TITLE
Feature request (chapters) and small issue (window position & size)

### ISSUE THREAD

**Issue by vertigo220** [UniqProject/BDInfo#8]
Would it be possible to have some sort of indicator whether a playlist contains chapters or not? This would save me an immense amount of time. It could be a separate column so I could sort by that.

Also, lately BDInfo hasn't been remembering the window position and size. Every time I use it, I have to make it smaller and move it off to the side, then when I reopen it, it's back in the center of the screen and very large. I'm not sure, but I think this started when I switched from Win7 to 10, though it may be due to upgrading to a newer version of BDInfo when I did that.

**Comment by UniqProject** [comment]
I cannot remember of BDInfo ever saving its window position, but I may have a look at it. I also will have a look how to display the chapter count properly.
This will take place in 2 weeks earliest, as I am on business trip for two weeks from today.

**Comment by UniqProject** [comment]
Features implemented in v0.7.5.1

**Comment by vertigo220** [comment]
Thanks for doing this. Unfortunately, now I'm having a problem that I'm assuming is caused by this change: When I minimize then restore BDInfo, it's shrunk down to just the title bar, almost as small as it can go, with just the icon and the minimize/maximize/close buttons visible. So I have to resize it to make it visible again, and the next time I minimize it it's shrunk again.

**Comment by UniqProject** [comment]
Should be fixed now

**Comment by vertigo220** [comment]
Confirmed. Thanks again!
